TPC3: Processador de Pessoas listadas nos Róis de Confessados

(publicado em 2023.02.28)

Construa agora um ou vários programas Python para processar o texto 'processos.txt' (procurar o ficheiro no Bb) com o intuito de calcular frequências de alguns elementos (a ideia é utilizar arrays associativos, dicionários em Python, para o efeito) conforme solicitado a seguir:

    a) Calcula a frequência de processos por ano (primeiro elemento da data);

    b) Calcula a frequência de nomes próprios (o primeiro em cada nome) e apelidos (o ultimo em cada nome) por séculos e apresenta os 5 mais usados;

    c) Calcula a frequência dos vários tipos de relação: irmão, sobrinho, etc.;

    d) Converta os 20 primeiros registos num novo ficheiro de output mas em formato Json.

In [14]:
import re
import matplotlib.pyplot as plt
from collections import Counter,OrderedDict
import math

lineRegex=re.compile(r"(?P<pasta>\d+)::(?P<data>\d\d\d\d-\d\d-\d\d)::(?P<nome>[^:]*)::(?P<pai>[^:]*)::(?P<mae>[^:]*)::(?P<obs>[^:]*)::")
data=[]
with open("processos.txt",'r') as file:
    for line in file.readlines():
        m = lineRegex.match(line)
        if m:
            data.append(m.groupdict())

A)

In [15]:
for line in data:
    ano,mes,dia=line['data'].split('-')
    line['ano']=ano
    line['mes']=mes
    line['dia']=dia
Counter(map(lambda x: x['ano'],data))

Counter({'1894': 74,
         '1909': 39,
         '1867': 53,
         '1896': 75,
         '1904': 51,
         '1901': 59,
         '1883': 34,
         '1900': 50,
         '1902': 83,
         '1880': 62,
         '1889': 70,
         '1908': 51,
         '1869': 39,
         '1862': 40,
         '1906': 63,
         '1856': 72,
         '1875': 15,
         '1892': 57,
         '1733': 1105,
         '1778': 1058,
         '1730': 1191,
         '1899': 79,
         '1898': 91,
         '1877': 46,
         '1910': 27,
         '1881': 64,
         '1907': 47,
         '1884': 44,
         '1879': 55,
         '1895': 78,
         '1897': 71,
         '1707': 112,
         '1689': 615,
         '1713': 263,
         '1824': 249,
         '1691': 584,
         '1703': 138,
         '1720': 172,
         '1890': 44,
         '1732': 2144,
         '1683': 140,
         '1863': 29,
         '1729': 41,
         '1694': 45,
         '1765': 9,
         '1754': 300,
         '1690': 179,
         '1755': 301,
         '1823': 213,
         '1708': 149,
         '1757': 31,
         '1699': 96,
         '1759': 88,
         '1712': 69,
         '1687': 92,
         '1738': 183,
         '1717': 267,
         '1684': 234,
         '1704': 178,
         '1688': 109,
         '1888': 70,
         '1734': 816,
         '1786': 352,
         '1798': 56,
         '1773': 482,
         '1821': 310,
         '1822': 303,
         '1809': 290,
         '1722': 454,
         '1680': 155,
         '1728': 440,
         '1716': 235,
         '1849': 118,
         '1777': 1133,
         '1851': 65,
         '1785': 794,
         '1857': 78,
         '1686': 182,
         '1784': 358,
         '1780': 217,
         '1727': 169,
         '1788': 410,
         '1719': 382,
         '1847': 130,
         '1799': 103,
         '1829': 161,
         '1787': 736,
         '1805': 109,
         '1819': 240,
         '1844': 194,
         '1891': 73,
         '1731': 882,
         '1760': 278,
         '1741': 31,
         '1725': 272,
         '1802': 90,
         '1827': 95,
         '1885': 8,
         '1807': 590,
         '1710': 193,
         '1692': 165,
         '1706': 112,
         '1858': 46,
         '1739': 54,
         '1826': 171,
         '1714': 314,
         '1762': 341,
         '1743': 53,
         '1724': 110,
         '1697': 26,
         '1852': 74,
         '1740': 11,
         '1855': 86,
         '1723': 127,
         '1859': 87,
         '1811': 234,
         '1817': 205,
         '1685': 231,
         '1905': 42,
         '1893': 77,
         '1865': 40,
         '1848': 124,
         '1911': 16,
         '1882': 50,
         '1735': 133,
         '1871': 35,
         '1903': 20,
         '1850': 114,
         '1825': 153,
         '1843': 294,
         '1860': 75,
         '1812': 257,
         '1846': 85,
         '1845': 126,
         '1701': 106,
         '1746': 48,
         '1868': 22,
         '1715': 88,
         '1803': 165,
         '1830': 171,
         '1761': 378,
         '1766': 9,
         '1672': 15,
         '1876': 40,
         '1698': 151,
         '1726': 85,
         '1679': 77,
         '1750': 53,
         '1711': 70,
         '1810': 45,
         '1721': 133,
         '1873': 46,
         '1831': 191,
         '1781': 208,
         '1818': 229,
         '1816': 350,
         '1783': 308,
         '1752': 80,
         '1866': 33,
         '1747': 58,
         '1771': 26,
         '1700': 81,
         '1682': 104,
         '1794': 57,
         '1742': 22,
         '1887': 42,
         '1836': 3,
         '1878': 76,
         '1886': 46,
         '1702': 137,
         '1767': 15,
         '1709': 144,
         '1779': 198,
         '1751': 107,
         '1681': 97,
         '1748': 45,
         '1678': 9,
         '1839': 85,
         '1770': 27,
         '1673': 18,
         '1792': 44,
         '1796': 86,
         '1828': 170,
         '1736': 46,
         '1737': 55,
         '1696': 27,
         '1853': 90,
         '1772': 122,
         '1718': 90,
         '1776': 36,
         '1804': 123,
         '1774': 37,
         '1832': 297,
         '1806': 106,
         '1820': 250,
         '1854': 112,
         '1861': 62,
         '1833': 194,
         '1841': 47,
         '1695': 39,
         '1705': 75,
         '1872': 42,
         '1874': 46,
         '1782': 153,
         '1693': 26,
         '1808': 305,
         '1838': 10,
         '1797': 46,
         '1660': 1,
         '1864': 55,
         '1870': 12,
         '1744': 39,
         '1800': 107,
         '1655': 2,
         '1795': 55,
         '1840': 36,
         '1764': 24,
         '1763': 28,
         '1676': 9,
         '1768': 26,
         '1753': 36,
         '1842': 36,
         '1671': 13,
         '1801': 57,
         '1814': 11,
         '1756': 72,
         '1815': 45,
         '1749': 27,
         '1775': 30,
         '1745': 46,
         '1834': 11,
         '1769': 16,
         '1793': 45,
         '1665': 2,
         '1813': 12,
         '1635': 1,
         '1616': 1,
         '1791': 6,
         '1758': 20,
         '1631': 2,
         '1664': 5,
         '1789': 12,
         '1623': 3,
         '1675': 8,
         '1677': 4,
         '1666': 6,
         '1663': 3,
         '1674': 2,
         '1668': 5,
         '1661': 1,
         '1630': 4,
         '1628': 7,
         '1670': 3,
         '1633': 2,
         '1632': 3,
         '1669': 3,
         '1636': 1,
         '1667': 1,
         '1634': 1,
         '1625': 2,
         '1656': 1,
         '1620': 1,
         '1629': 1,
         '1622': 1,
         '1627': 2,
         '1790': 1,
         '1658': 1,
         '1650': 1,
         '1662': 1})

B)

In [20]:
#5 mais usados
c=Counter(map(lambda x:x['nome'],data))
c.most_common(5)
primeiroNome={}
ultimoNome={}
for line in data:
    seculo = math.ceil(int(line['ano'])/100)
    nomes = line['nome'].split(' ') 
    if seculo not in primeiroNome:
        primeiroNome[seculo]=[]
    if seculo not in ultimoNome:
        ultimoNome[seculo]=[]
    primeiroNome[seculo].append(nomes[0])
    ultimoNome[seculo].append(nomes[-1])
primeiroNome=sorted(primeiroNome.items(), key=lambda x: x[0])
for k,v in primeiroNome:
    print("seculo",k)
    print("primeiro nome:",*Counter(v).most_common(5))
    print("ultimo nome:",*Counter(ultimoNome[k]).most_common(5))

seculo 17
primeiro nome: ('Manuel', 508) ('Joao', 501) ('Antonio', 420) ('Francisco', 356) ('Domingos', 231)
ultimo nome: ('Silva', 155) ('Pereira', 135) ('Costa', 127) ('Araujo', 115) ('Carvalho', 93)
seculo 18
primeiro nome: ('Manuel', 3797) ('Joao', 2924) ('Antonio', 2799) ('Jose', 2489) ('Francisco', 2033)
ultimo nome: ('Pereira', 956) ('Silva', 888) ('Costa', 768) ('Carvalho', 706) ('Araujo', 653)
seculo 19
primeiro nome: ('Jose', 2075) ('Antonio', 1817) ('Manuel', 1487) ('Joao', 1245) ('Francisco', 840)
ultimo nome: ('Pereira', 426) ('Silva', 422) ('Costa', 346) ('Sousa', 301) ('Araujo', 262)
seculo 20
primeiro nome: ('Antonio', 91) ('Jose', 76) ('Manuel', 76) ('Joao', 34) ('Joaquim', 17)
ultimo nome: ('Silva', 25) ('Costa', 19) ('Oliveira', 16) ('Pereira', 14) ('Ferreira', 11)

C)
Calcula a frequência dos vários tipos de relação: irmão, sobrinho, etc.;

In [33]:
r = re.compile(r",(Irmao|Irma|Sobrinho|Sobrinha|Pai|Mae|Filho|Filha|Tio|Tia)\s")
l=[]
for obs in map(lambda x:x['obs'],data):
    j=r.findall(obs)
    if j!=[]:
        l+=j
Counter(l)

Counter({'Tio': 4980, 'Sobrinho': 3478, 'Irmao': 508})

d) Converta os 20 primeiros registos num novo ficheiro de output mas em formato Json.

In [34]:
import json
with open('data.json', 'w') as f:
    json.dump(data[:20], f)